# Generated by Django 5.0.3 on 2024-03-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_comment_options_alter_createblog_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='createblog',
            name='image',
            field=models.ImageField(default='', upload_to='media'),
        ),
        migrations.AddField(
            model_name='createblog',
            name='intro',
            field=models.TextField(default=''),
        ),
    ]
